### ISSUE TITLE
Replace StaticArrays dependency with `ismutable`

### ISSUE THREAD

**Issue by gdalle** [JuliaDiff/DiffResults.jl#28]
Maybe we could implement the mutable and immutable result types by checking `ismutable(value)` and `any(ismutable, derivs)`?
It's not type-inferrable in the strict sense but perhaps constant propagation will get us most of the way there?

**Comment by devmotion** [comment]
AFAICT `ismutable` is not sufficient to determine whether an array is mutable, ie. whether `setindex!` is supported - it seems to be merely a trait to distinguish between (im)mutable types. For instance, according to `ismutable` immutable wrapper types are not mutable:
```julia
julia> A = rand(3, 1)';

julia> ismutable(A)
false

julia> A[1, 2]
0.8835110796659092

julia> A[1, 2] = 0.0
0.0

julia> A[1, 2]
0.0
```

You'd need something like `ArrayInterface.ismutable`:
```julia
julia> using ArrayInterface

julia> ArrayInterface.ismutable(A)
true
```

**Comment by gdalle** [comment]
That's fair, although mildly disappointing I guess ^^
